apiVersion: v1
description: A Helm chart for Docker Registry
name: docker-registry
version: 3.0.0
appVersion: 2.8.1
home: https://hub.docker.com/_/registry/
maintainers:
  - name: Labyrinth Labs
    email: contact@lablabs.io
    url: https://lablabs.io
sources:
  - https://github.com/docker/distribution-library-image
